Ot148 20 testimonials
alkemyTech/OT148-JAVA pull request #15
Opened 2022-02-21 16:47 UTC by Darnasus

Testimonial Mapper

2022-02-21 18:40 UTC, sginabreda commented on src/main/java/com/alkemy/ong/domain/Testimonial.java
> +    public class Testimonial {
Hay que aplicarle formato a este archivo 👌🏼  ctrl+alt+L en windows.

2022-02-21 18:40 UTC, sginabreda commented on src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
> +    public static TestimonialModel mapDomainToModel (Testimonial testimonialDomain){
Hay un espacio de más entre el nombre del método y el paréntesis.

2022-02-21 18:40 UTC, sginabreda commented on src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
> +import com.alkemy.ong.repository.model.TestimonialModel;
Donde está `TestimonialModel`? Porque no está en este PR.

2022-02-21 20:17 UTC, sginabreda requested changes

2022-02-21 20:17 UTC, sginabreda commented on src/main/java/com/alkemy/ong/domain/Testimonial.java
> +}
Esta llave está de mas. Luego hay que aplicarle formato al archivo ya que está mal indentado.

2022-02-21 20:17 UTC, sginabreda commented on src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
> +        Testimonial testimonialDomain = Testimonial.builder().
Falta asignar el id

2022-02-21 20:17 UTC, sginabreda commented on src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
> +        TestimonialModel testimonialModel = TestimonialModel.builder().
Falta asignar el id.

2022-02-21 20:17 UTC, sginabreda commented on src/main/java/com/alkemy/ong/repository/TestimonialRepository.java
> +    public interface TestimonialRepository extends CrudRepository<TestimonialRepository,Long> {
La clase está mal indentada, hay que corregir eso. El primer parámetro de CrudRepository recibe la clase que se va a guardar, en este caso `TestimonialModel`.

2022-02-21 20:17 UTC, sginabreda commented on src/main/java/com/alkemy/ong/repository/model/TestimonialModel.java
> +    private LocalDateTime creationDate;
Agreguemos el método de `@PrePersist` para este campo. Fijate en lo que ya está mergeado que hay varios ejemplos.

2022-02-22 13:50 UTC, Darnasus commented on src/main/java/com/alkemy/ong/domain/Testimonial.java
> +}
Correciones realizadas

2022-02-22 13:51 UTC, Darnasus commented on src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
> +        TestimonialModel testimonialModel = TestimonialModel.builder().
Id asignado

2022-02-22 13:51 UTC, Darnasus commented on src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
> +        Testimonial testimonialDomain = Testimonial.builder().
Id asignado

2022-02-22 13:52 UTC, Darnasus commented on src/main/java/com/alkemy/ong/repository/model/TestimonialModel.java
> +    private LocalDateTime creationDate;
Añadido

2022-02-22 14:24 UTC, sginabreda commented on src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
> +        content(testimonialModel.getContent()).build();
Fijate que en los dos métodos tenes 2 `build()`. Hay uno que está de mas, el IntelliJ te debería tirar warning.

2022-02-22 18:26 UTC, sginabreda commented
Los archivos de Testimonials ya no están mas, al parecer los borraste en algun commit. Te diría que este PR lo cierres, en tu repo local te traigas todos los ultimos cambios de main y te armes de ahi la rama de nuevo, y luego armes otro PR.

2022-02-23 13:41 UTC, closed without merging