OT148-25 EndpointLogin
alkemyTech/OT148-JAVA pull request #19
Opened 2022-02-22 18:39 UTC by Sebavarg

OT148-25-Endpoint de Autenticacion 
SUMMARY
Classes modified
UserController
UserService
UserMapper
UserRepository

New Classes
 UserLoginPassswordInvalid
![WhatsApp Image 2022-02-22 at 15 28 39 (1)](https://user-images.githubusercontent.com/92404002/155197242-13600e6a-46d6-44dc-b9a4-77cc9ecf8925.jpeg)
![WhatsApp Image 2022-02-22 at 15 28 39](https://user-images.githubusercontent.com/92404002/155197245-8fc3e1d0-5fb6-4a69-b509-c4e372218ca3.jpeg)
![WhatsApp Image 2022-02-22 at 15 28 39 (2)](https://user-images.githubusercontent.com/92404002/155197228-9b6dcaa1-2984-490a-9fc3-9771249c1de9.jpeg)

2022-02-22 18:40 UTC, Sebavarg commented
I apologize for having made a single commit, I was very focused on my local repo and I am learning to work as a team, I hope to improve next time

2022-02-22 19:38 UTC, sginabreda requested changes

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +        ErrorDTO loginUserNotFound =
La variable debería llamarse de una forma que indique mas a que se refiere este error, es decir, a una contraseña inválida.

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    public ResponseEntity<ErrorDTO> handlerUserLoginPasswordInvalid (UserLoginPasswordInvalid ex) {
Hay un espacio de mas despues del nombre.

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/dto/ErrorDTO.java
> +public class ErrorDTO {
Este y otras clases ya deberían estar mergeadas, por lo que no deberían aparecer en este PR. Cuando puedas te traes los ultimos cambios de main?

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/exception/UserLoginPasswordInvalid.java
> +public class UserLoginPasswordInvalid extends Exception{
El nombre de la clase debería indicar que es una exception.

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +        User user = User.builder().password(userLoginDTO.getPassword()).email(userLoginDTO.getEmail()).build();
Aplicar indentación y formato acá 🙏🏼

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/repository/UserRepository.java
> +    boolean existsByEmail (String email);
Estos dos métodos los podes combinar en uno solo que sea `findByEmail` y que retorne un `Optional<UserModel>`. De ese modo, cuando lo busques, luego chequeas si `isPresent()`: si no lo está, tiras la excepcion.

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/security/SecurityConfig.java
> +        http.csrf().disable().authorizeRequests().antMatchers("/auth/register/**", "/h2/**", "/users","/auth/login/**").permitAll().anyRequest().authenticated();
Podes combinar todo en uno y directamente poner `"/auth/**"`, asi no tenemos el de register y el de login separados.

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/service/UserService.java
> +    private Boolean matchEncryptedPassword(String password, String passwordEncrypted) {
`passwordMatches` creería que suena un poco mejor.

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/service/UserService.java
> +            (String password, UserModel userModel) throws UserLoginPasswordInvalid {
Fijate de correr el formateador acá, porque me parece que quedó mal. Por lo menos desde acá en Github no reconoce el `throws`.

2022-02-22 19:38 UTC, sginabreda commented on src/main/java/com/alkemy/ong/service/UserService.java
> +    private UserDTO getUserDTO
Va a haber que revisar el nombre de este método ya que no solo obtiene un UserDto, también chequea las contraseñas 👆🏼

2022-02-22 19:41 UTC, sginabreda commented on src/main/java/com/alkemy/ong/service/UserService.java
> +    public UserDTO loginUser(User user) throws UserNotFoundException, UserLoginPasswordInvalid {
El tipo que retorna está mal, debería ser solo `User` y no un Dto. Al parecer me lo comí en los otros métodos 😬  ya lo vamos a corregir. El mapeo a Dto lo tenes que hacer en el controller.

2022-02-22 19:41 UTC, sginabreda commented
Fijate cuando puedas de traerte los cambios de main asi ya no salta el mensaje de que tenes conflictos 👌🏼

2022-02-22 21:09 UTC, Sebavarg commented on src/main/java/com/alkemy/ong/service/UserService.java
> +            (String password, UserModel userModel) throws UserLoginPasswordInvalid {
como es eso de correr el formateador?

2022-02-22 22:15 UTC, sginabreda commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +        User user = User.builder().password
Corregir formato acá, despues del builder() deberíamos tener un campo por renglón:
```suggestion
        User user = User.builder()
        .password(...)
        .email(...)
        .build();
```

2022-02-22 22:15 UTC, sginabreda commented on src/main/java/com/alkemy/ong/exception/NotExistPasswordException.java
> +public class NotExistPasswordException extends Exception{
Por el momento llamemosla `InvalidPasswordException`.

2022-02-22 22:15 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    public ResponseEntity<ErrorDTO> handlerUserLoginPasswordInvalid (NotExistPasswordException ex) {
`handleInvalidPasswordException` pasaría a llamarse.

2022-02-22 22:16 UTC, sginabreda commented on src/main/java/com/alkemy/ong/service/UserService.java
> +            (String password, UserModel userModel) throws UserLoginPasswordInvalid {
Ctrl + Alt + L. El otro día lo hiciste con uno de los alts, porque el otro no andaba.

2022-02-22 23:29 UTC, Sebavarg commented on src/main/java/com/alkemy/ong/repository/UserRepository.java
> +    boolean existsByEmail (String email);
Santi  a mi me parece mas claro la forma en la que lo escribí yo, tal vez vos con tu experiencia crees que no, pero hasta esta bueno que uno te devuelve un boolean y otro un UserModels, yo no suelo usar el isPresent(), pero si me decis que lo cambie, lo cambio

2022-02-22 23:29 UTC, Sebavarg commented on src/main/java/com/alkemy/ong/service/UserService.java
> +            (String password, UserModel userModel) throws UserLoginPasswordInvalid {
ah sisis , me tengo que tatuar ese comando ;)

2022-02-23 13:34 UTC, sginabreda approved these changes

2022-02-23 13:40 UTC, sginabreda commented on src/main/java/com/alkemy/ong/repository/UserRepository.java
> +    boolean existsByEmail (String email);
No hay problema 👌🏼  en estos casos no va a pasar nada, porque vamos a tener pocos registros, pero en una aplicación que tiene muchos registros y mucho tráfico, al hacer primero una busqueda para ver si existe, y luego traerte el registro, estas haciendo dos consultas a la base de datos, y eso puede ser muy costoso.
Teniendo solo un `Optional<UserModel> findByEmail(String email);` podes hacer:
```suggestion
    public void loginUser(User user) {
    Optional<UserModel> optionalUser = userRepository.findByEmail(user.getEmail());
    if (!optionalUser.isPresent()) {
         throw UserNotFoundException();
    }
    return getUserLoginChecked(user, optionalUser);
```

2022-02-23 14:20 UTC, merged