Ot148 74 comments
alkemyTech/OT148-JAVA pull request #69
Opened 2022-03-08 15:01 UTC by Sebavarg

Comments Class Created

SUMMARY
New classes
- domain/ Comment
- service/ CommentService
- controller/ CommentController
- mapper/CommentMapper
- AppConfig/ Bean CommentService Added
- Dto/ CommentDTO
- Repository/ CommentRepository
- Model/ CommentModel

EVIDENCE

![image](https://user-images.githubusercontent.com/92404002/157264032-ad225ca2-fc0a-4608-b8fd-81a351533414.png)

Reviewer Santiago
Better later than never XD

2022-03-08 20:48 UTC, sginabreda requested changes
Estaba chequeando el scope de este ticket y en realidad es nada mas lo de model y repository. El de la creación (y por lo tanto uso de controller y service) es el OT148-76 👍🏼

2022-03-08 20:48 UTC, sginabreda commented on src/main/java/com/alkemy/ong/config/AppConfig.java
> +    @Bean
Espacio entre métodos.

2022-03-08 20:48 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/CommentController.java
> +    public ResponseEntity<CommentDTO> storeContact(@Valid @RequestBody CommentDTO commentDTO) {
`saveComment` o `createComment`

2022-03-08 20:48 UTC, sginabreda commented on src/main/java/com/alkemy/ong/domain/Comment.java
> +    private Long user_id;
Usamos camelCase para los atributos: `userId`.

2022-03-08 20:48 UTC, sginabreda commented on src/main/java/com/alkemy/ong/dto/CommentDTO.java
> +    private Long user_id;
Me suena a que el userId igualmente lo vamos a tener que sacar nosotros del jwt por ejemplo, porque no tiene mucho sentido pedirlo en el body.

2022-03-09 13:09 UTC, sginabreda commented on src/main/java/com/alkemy/ong/dto/CommentDTO.java
> +    private Long news_id;
camelCase en los atributos 👍🏼

2022-03-09 13:09 UTC, sginabreda commented on src/main/resources/application.properties
> -aws.s3.bucketName=${AWS_BUCKET_NAME}
Por qué los estas borrando ? 😢

2022-03-09 13:22 UTC, Sebavarg commented on src/main/resources/application.properties
> -aws.s3.bucketName=${AWS_BUCKET_NAME}
pense q no habia que escribir nada de amazon en el properties y que cada uno iba a pegar las contraseñas para correr el programa

2022-03-09 14:04 UTC, sginabreda commented on src/main/resources/application.properties
> -aws.s3.bucketName=${AWS_BUCKET_NAME}
Por favor lee el PR en el que subi estos cambios: https://github.com/alkemyTech/OT148-JAVA/pull/45

2022-03-09 14:04 UTC, sginabreda approved these changes

2022-03-09 15:40 UTC, merged