[OT148-82] Adding pagination to Members
alkemyTech/OT148-JAVA pull request #76
Opened 2022-03-11 19:03 UTC by Tescelin16

2022-03-11 21:19 UTC, sginabreda requested changes
Te tiro un centro con el ticket.. Como en la descripción dice "se deberán mostrar los resultados y las urls para la página anterior y siguiente (si corresponden)", entonces en tu respuesta en vez de ser una lista nada mas, vas a tener un objeto mas o menos como el siguiente:
`{ members: [], previousPage: "url", nextPage: "url" }`
Otro dato a tener en cuenta es que, si vos no recibis un numero de pagina, el default debería ser 0, pero al filtrar siempre es la pagina que recibis + 1. Fijate que creo que el método `chunk` de una lista te podría llegar a servir.

2022-03-11 21:19 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +    @GetMapping("/page/{page}")
Creo que se entendió mal el scope del ticket.. lo que se quiere hacer es que cuando vos hagas un request a `/members` (es decir, el endpoint de arriba, el getAll) te muestre de a 10 objetos. No había que crear un endpoint nuevo 👌🏼

2022-03-14 00:23 UTC, Tescelin16 commented
[
![endpoint GET members p 1](https://user-images.githubusercontent.com/82984320/158086036-4998f1f0-6f8f-42ae-b892-96c19ce5807e.png)
![endpoint GET members p 2](https://user-images.githubusercontent.com/82984320/158086041-8c75bd51-c4a1-4753-8886-0f97cb47d83d.png)
![endpoint GET members p 3](https://user-images.githubusercontent.com/82984320/158086042-4275fabe-b436-494e-be4e-6db8541e666a.png)
](url)

2022-03-14 00:57 UTC, sginabreda reviewed
Va queriendo 💪🏼

2022-03-14 00:57 UTC, sginabreda commented on src/main/java/com/alkemy/ong/dto/MemberApiResponse.java
> +public class MemberApiResponse {
Cambiemos el nombre a `MemberListDTO`

2022-03-14 00:57 UTC, sginabreda commented on src/main/java/com/alkemy/ong/dto/MemberApiResponse.java
> +@Data
Y viendo las capturas que subiste, en el caso que no haya próxima pagina o pagina previa se ve el "null". Agreguemos la annotation para que no se vean los null.

2022-03-14 00:57 UTC, sginabreda commented on src/main/java/com/alkemy/ong/service/MemberService.java
> -    @Transactional
No hace más falta esta annotation?

2022-03-14 00:57 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +        response.setMembers(members.getContent().stream().map(MemberMapper::mapDomainToDTO).collect(Collectors.toList()));
Siento que todo esto lo podemos meter en un constructor de `MemberListDTO`. Incluso lo de `currentContextPath` lo podes meter en un ContextUtils ya que seguro se va a usar en otro lugar.

2022-03-14 13:41 UTC, Tescelin16 commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +        response.setMembers(members.getContent().stream().map(MemberMapper::mapDomainToDTO).collect(Collectors.toList()));
Genial Santi. Estoy tratando de hacer el contructor y mandar de vuelta el PR...lo que no entendí bien es lo de ContextUtils...dónde lo tendría que meter, también en el constructor?

2022-03-14 13:41 UTC, Tescelin16 commented on src/main/java/com/alkemy/ong/service/MemberService.java
> -    @Transactional
Si pienso que es mejor ponerla.

2022-03-14 14:01 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +        response.setMembers(members.getContent().stream().map(MemberMapper::mapDomainToDTO).collect(Collectors.toList()));
Nono, lo de ContextUtils lo podes meter en la carpeta utils. Fijate que Pablo ya agregó un SecurityUtils en esa carpeta si no me equivoco 👍🏼

2022-03-14 18:53 UTC, sginabreda reviewed
2 comentarios más de formato nomás, ya está ok 👍🏼

2022-03-14 18:53 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +    @GetMapping()
Los paréntesis acá no son necesarios 👍🏼

2022-03-14 18:53 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +
Línea de más.

2022-03-14 19:38 UTC, merged