[OT148-76] Creation comment
alkemyTech/OT148-JAVA pull request #77
Opened 2022-03-11 19:34 UTC by PabloD97

- Added '/comments' endpoint for creation Comment
- Added createComment() method in CommentService
- Added CommentCreationDTO in dto

Show responses 
![creationComment201](https://user-images.githubusercontent.com/42455630/157941954-14acbd30-7d94-4a30-918d-4da4bb8c4467.png)
![commentNewsNotFound](https://user-images.githubusercontent.com/42455630/157942028-db5e7639-42f5-4ea7-8c2e-79ba17658717.png)

2022-03-11 21:06 UTC, sginabreda requested changes

2022-03-11 21:06 UTC, sginabreda commented on src/main/java/com/alkemy/ong/dto/CommentCreationDTO.java
> +    private Long userId;
Este saquemoslo desde el jwt (hay que agregarlo primero en el JwtDTO). No creo que uno tenga que acordarse su userId para crear un comentario, mas que nada por eso 😄

2022-03-11 21:06 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
> +    private ResponseEntity<ErrorDTO> handleUserNotFound(UserNotFoundException ex) {
Este no va a hacer falta despues del cambio de userId.

2022-03-11 22:54 UTC, PabloD97 commented on src/main/java/com/alkemy/ong/dto/CommentCreationDTO.java
> +    private Long userId;
Tiene sentido, pero los criterios de aceptación me pide que me asegure que ese campo se mande.
Lo dejo así o hago lo de jwt?

2022-03-11 23:51 UTC, PabloD97 commented on src/main/java/com/alkemy/ong/dto/CommentCreationDTO.java
> +    private Long userId;
En el caso de hacerlo con jwt, no podría usar el metodo de UserService `getAuthenticatedUser()` que me devuelve un User en base al token y de ahí extraer el id?

2022-03-11 23:57 UTC, sginabreda commented on src/main/java/com/alkemy/ong/dto/CommentCreationDTO.java
> +    private Long userId;
Esa es una forma. Lo único malo de eso es que tenes que incluir al jwt en la firma del método (como header) y no queda tan bien.
Fijate si lo podes hacer usando el SecurityContext (que es el que tiene seteado el usuario), pero antes vas a tener que cambiar el jwt para que tambien tenga el id de usuario.
Si ves que es mucha vuelta, hace esto último del getAuthenticationHeader 👌🏻

2022-03-12 05:22 UTC, PabloD97 commented on src/main/java/com/alkemy/ong/dto/CommentCreationDTO.java
> +    private Long userId;
Hice lo de SecurityContext, pero en vez de hacer `.getName()` tuve que hacer `.getPrincipal()`. El primero me arrojaba null y el otro me traía todos los datos del usuario logueado.

2022-03-12 15:09 UTC, sginabreda approved these changes

2022-03-12 15:40 UTC, merged