Ot148 88 add documentation testimonials
alkemyTech/OT148-JAVA pull request #81
Opened 2022-03-13 20:50 UTC by Sebavarg

SUMMARY
Testimonial Controller has become  in an interface
Testimonial Resource has been created and implement the firts one.

EVIDENCE
![image](https://user-images.githubusercontent.com/92404002/158078572-92e26da0-583e-4c11-9a69-d8b1278d4e57.png)
![image](https://user-images.githubusercontent.com/92404002/158078596-85110262-2854-4758-8436-fad39c115e5f.png)
![image](https://user-images.githubusercontent.com/92404002/158078620-4f821cdc-bebe-4e7a-af30-cfff320e7bc8.png)

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    ResponseEntity<TestimonialDTO> updateTestimonials
`updateTestimonial`

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
> +@Tag(name = "Testimonials", description = "Create, update show and delete Testimonials")
Esto debería ir en el controller. Fijate cuando abris la documentación en un navegador que hay dos secciones para testimonial: una solo con este tag, y todo lo demás que viene de la interface controller.

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +            @ApiResponse(responseCode = "404", description = "Testimonials not found",
`Testimonial not found`

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +                                    schema = @Schema(implementation = TestimonialDTO.class))}),
Esto no hace falta ya que cuando borramos la entidad, solo devolvemos 200 👍🏼

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +            @ApiResponse(responseCode = "200", description = "Update Testimonials by id",
`Update Testimonial by id`

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    @Operation(summary = "Update a Testimonials by id")
`Update Testimonial by id`

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    createTestimonial(@Valid @RequestBody TestimonialCreationDTO testimonialCreationDTO);
Esto lo podemos poner en una misma línea no?

2022-03-14 02:08 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +            summary = "Add new Testimonials",
`Add new Testimonial`

2022-03-14 02:08 UTC, sginabreda commented
Va bieeen 👏🏼

2022-03-14 19:09 UTC, Sebavarg commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +            @ApiResponse(responseCode = "200", description = "Update Testimonials by id",
Santi igualmente me va a faltar , asi que no lo voy a pullear pq en testimonialsPagination voy a modificar el Controller y voy a necesitar Documentarlo tambien asi q no puedo pisarme con este ticket el anterior tendria q terminar la paginacion primero pero estoy esperando q aprobes un PR a ver si me guio

2022-03-14 19:10 UTC, Sebavarg commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +            @ApiResponse(responseCode = "200", description = "Update Testimonials by id",
es como que los tres tickets que me tocaron son correlativos y no puedo romper esa correlatividad, ahora en la tarde me pongo a ver si le doy en la tecla con la paginacion

2022-03-14 19:39 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +            @ApiResponse(responseCode = "200", description = "Update Testimonials by id",
Eso no te preocupes 👌🏼  la parte de la documentación que quede afuera, la seguimos después. O abris otro PR para agregar ese faltante en la docu de swagger. Asi no se atrasa este ticket y sumas puntos de esto en el sprint

2022-03-15 00:27 UTC, sginabreda approved these changes

2022-03-15 00:54 UTC, sginabreda requested changes

2022-03-15 00:54 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +public interface TestimonialController {
Acá faltaría agregarle la annotation de `@Api` para que te junte todo en la misma sección. Si te fijas cuando entras a la documentación de swagger de esta app, hay una sección de "Testimonials" (que no tiene nada) y otra de testimonial-resource. Queremos que estén juntas 👌🏼

2022-03-15 19:19 UTC, sginabreda commented on src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
> +@Api (value= "testimonialResource", tags = {"testimonials"})
Si este tag de "testimonials" lo pones con la T minuscula, te sigue poniendo dos secciones distintas 👍🏼  Como en el controller creaste el tag `Testimonials` acá vas a tener que poner ese mismo valor.

2022-03-15 20:44 UTC, sginabreda approved these changes
Mismo acá. Fijate de traerte los cambios de main primero y cuidado con los conflictos 👍🏼

2022-03-15 21:50 UTC, merged